# Generated by Django 3.0.7 on 2020-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lower_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='upper_bound',
            field=models.IntegerField(default=0),
        ),
    ]
