# Generated by Django 3.0.7 on 2020-07-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number_generation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='guess',
            old_name='user',
            new_name='created_by',
        ),
    ]
